apiVersion: apps/v1
kind: Deployment
metadata:
  name: horpakjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: horpakjs
  template:
    metadata:
      labels:
        app: horpakjs
    spec:
      containers:
        - name: horpakjs
          image: hongjsx/horpakjs
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mnt
              mountPath: /homes/app/.env.production
              subPath: .env
              readOnly: true
            # - name: mnt
            #   mountPath: /homes/app/.env.local
            #   subPath: .dev
            #   readOnly: true
      volumes:
        - name: mnt
          configMap:
            name: horpakjs-env
---
apiVersion: v1
kind: Service
metadata:
  name: horpakjs-service
spec:
  type: NodePort
  selector:
    app: horpakjs
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 30001
      nodePort: 30001
