import type { AppProps } from 'next/app';
import { SessionProvider } from 'next-auth/react';
import Head from 'next/head';
import Providers from '../Providers';
import '../styles/globals.css';

const PUBLIC_PATHS = ['/auth/signin', '/unauthorized'];

const MyApp = ({ Component, pageProps, router: { route } }: AppProps) => {
  const publicAccess = PUBLIC_PATHS.some((path) => route.startsWith(path));

  return (
    <SessionProvider session={pageProps.session}>
      <Head>
        <title>Hong.JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
        />
      </Head>
      {!publicAccess && (
        <Providers>
          <Component {...pageProps} />
        </Providers>
      )}
      {publicAccess && <Component {...pageProps} />}
    </SessionProvider>
  );
};

export default MyApp;
