import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { SessionProvider } from 'next-auth/react';
import Providers, { AuthProvider } from '../Providers';
import Layout from 'components/layout/Layout';

const PUBLIC_PATHS = ['/auth/signin'];

const MyApp = ({ Component, pageProps, router: { route } }: AppProps) => {
  const requireAuth = !PUBLIC_PATHS.some((path) => route.startsWith(path));
  console.log(route);
  return (
    <SessionProvider session={pageProps.session}>
      <Providers>
        <Head>
          <title>Hong.JS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
          />
        </Head>
        {requireAuth && (
          <AuthProvider>
            <Layout>
              <Component {...pageProps} />
            </Layout>
          </AuthProvider>
        )}
        {!requireAuth && <Component {...pageProps} />}
      </Providers>
    </SessionProvider>
  );
};

export default MyApp;
