import React from 'react';
import type { NextPage, GetServerSideProps } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import { signOut, getSession } from 'next-auth/react';
import { Session } from 'next-auth';
import { Button, Typography } from '@mui/material';
import styles from '../styles/Home.module.css';

const Home: NextPage<PageProps> = (props) => {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!props.session && (
          <div>
            <Button onClick={() => router.push('/signin')}>Signin</Button>
          </div>
        )}
        {props.session && (
          <React.Fragment>
            <Image
              src={props.session.user?.image || ''}
              alt="pic"
              width={100}
              height={100}
            />
            <Typography>{props.session.user?.name}</Typography>
            <Button onClick={() => signOut()}>Sign out</Button>
          </React.Fragment>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

type PageProps = {
  session: Session | null;
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  const _props: PageProps = { session: session };
  return { props: _props };
};
