import React, { useEffect } from 'react';
import type { NextPage, GetServerSideProps } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import { signOut, getSession } from 'next-auth/react';
import { Button, Typography } from 'components/mui';

import { HomePageProps } from 'config/types';
import styles from 'styles/Home.module.css';

const Home: NextPage<HomePageProps> = ({ session }) => {
  const router = useRouter();
  useEffect(() => {
    if (!session) {
      router.push('/auth/signin');
    }
  }, [router, session]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {session && (
          <React.Fragment>
            <Image
              src={session.user?.image || ''}
              alt="user-pic"
              width={100}
              height={100}
            />
            <Typography>{session.user?.name}</Typography>
            <Button onClick={() => signOut()}>Sign out</Button>
          </React.Fragment>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  const _props: HomePageProps = { session };
  return { props: _props };
};

export default Home;
