const reportSchema = {
  type: "object",
  properties: {
    room: { type: "integer" },
    name: { anyOf: [{ type: "number" }, { type: "string" }] },
    water_start: { type: "integer" },
    water_end: { type: "integer" },
    water_unit_price: { type: "number" },
    water_unit: { type: "integer" },
    water_min_cost: { type: "number" },
    water_cost: { type: "number" },
    electric_start: { type: "integer" },
    electric_end: { type: "integer" },
    electric_unit_price: { type: "number" },
    electric_unit: { type: "integer" },
    electric_cost: { type: "number" },
    room_cost: { type: "number" },
    share_cost: { type: "number" },
    internet_cost: { type: "number" },
    penalty_cost: { type: "number" },
    arrear: { type: "number" },
    electric_extra: { type: "string" },
    electric_extra_cost: { type: "number" },
    water_extra: { type: "string" },
    water_extra_cost: { type: "number" },
    other1: { anyOf: [{ type: "number" }, { type: "string" }] },
    other1_cost: { type: "number" },
    other2: { anyOf: [{ type: "number" }, { type: "string" }] },
    other2_cost: { type: "number" },
    other3: { anyOf: [{ type: "number" }, { type: "string" }] },
    other3_cost: { type: "number" },
    bank_id: { type: "number" },
    total: { type: "number" },
  },
  required: [
    "room",
    "name",
    "water_start",
    "water_end",
    "water_unit_price",
    "water_unit",
    "water_min_cost",
    "water_cost",
    "electric_start",
    "electric_end",
    "electric_unit_price",
    "electric_unit",
    "electric_cost",
    "room_cost",
    "share_cost",
    "internet_cost",
    "penalty_cost",
    "arrear",
    "electric_extra",
    "electric_extra_cost",
    "water_extra",
    "water_extra_cost",
    "other1",
    "other1_cost",
    "other2",
    "other2_cost",
    "bank_id",
    "total",
  ],
  additionalProperties: false,
};

export default reportSchema;
